apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/NC-R/argocd.git
        revision: main
        files:
          - path: infra/environments/infra/apps/*.yaml
  template:
    metadata:
      name: 'infra-{{ .app }}'
      annotations:
        {{- if ne (default "helm" .type) "app" }}
        argocd-image-updater.argoproj.io/image-list: '{{ .app }}=reg.rsn-okd.netcloud.lab:8880/{{ .app }}/{{ .app }}'
        argocd-image-updater.argoproj.io/{{ .app }}.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
        {{- end }}
    spec:
      project: '{{ default "default" .project | default .app }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      source:
        repoURL: https://github.com/NC-R/argocd.git
        targetRevision: main
        path: 'apps/{{ .app }}'
        {{- if eq (default "helm" .type) "app" }}
        directory:
          recurse: true
          include:
            - application.yaml
        {{- else }}
        helm:
          releaseName: '{{ .app }}'
          valuesObject:
            route:
              host: '{{ .app }}.{{ .baseDomain }}'
        {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
