image:
  repository: reg.rsn-okd.netcloud.lab:8880/app1/app1
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

route:
  enabled: true
  host: ""

service:
  type: ClusterIP
  port: 80
