apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app1
  namespace: argocd
spec:
  description: "Project for all app1 deployments"
  sourceRepos:
    - '*'                     # alle Repos erlaubt
  destinations:
    - server: '*'             # alle Cluster erlaubt
      namespace: '*'          # alle Namespaces erlaubt
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
