apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo
  namespace: argocd
spec:
  description: "Project for all kargo deployments"
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
