apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: kargo                 # oder "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  sources:
    - repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
      path: .
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/apps/kargo/values.yaml
    - repoURL: https://github.com/NC-R/argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
