apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: kargo
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: v1.7.2
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          value: $2y$10$UubvHYx82W4Wrvobwt8gbubFG52R9kpKxG18PKL5I77YX0n07NSeK
        - name: api.adminAccount.tokenSigningKey
          value: v2dRVE2M0m843sj1byWVAe9AopAXrum3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true