apiVersion: app.k8s.io/v1alpha1
kind: Application
metadata:
  name: app1
  labels:
    app.kubernetes.io/part-of: app1
spec:
  componentKinds:
    - group: apps
      kind: Deployment
    - group: route.openshift.io
      kind: Route
    - group: v1
      kind: Service
  selector:
    matchLabels:
      app.kubernetes.io/part-of: app1
