apiVersion: v1
kind: Service
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ include "app1.name" . }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "app1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
