apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kargo
    namespace: argocd
spec:
    project: {{ .Values.argocdProject | default "default" | quote }}
    destination:
        namespace: {{ .Release.Namespace | default "kargo" | quote }}
        server: https://kubernetes.default.svc
    source:
        repoURL: ghcr.io/akuity/kargo-charts
        chart: kargo
        targetRevision: v1.7.2
        helm:
            valuesObject:
                api:
                    host: {{ .Values.kargo.host | quote }}
                    adminAccount:
                        passwordHash: "$2y$10$klXQ2IfS5vsjxoLU2StCm.gPEoRgUczOT9CsxnwiBLU9XN9akBSg."
                        tokenSigningKey: "NNKuuEiu0FwwdriTlHyn6sWSJgPEc9Ri"
                    ingress:
                        enabled: {{ not .Values.route.enabled }}
                        ingressClassName: "openshift-default"
                        tls:
                            selfSignedCert: {{ .Values.kargo.selfSignedCert }}
                controller:
                    argocd:
                        namespace: "argocd"
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
