apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kargo
    namespace: argocd
spec:
    source:
        repoURL: ghcr.io/akuity/kargo-charts
        chart: kargo
        targetRevision: 1.7.2
        helm:
            valuesObject:
                api:
                    host: {{ .Values.kargo.host | quote }}
                    adminAccount:
                        passwordHash: "$2y$10$klXQ2IfS5vsjxoLU2StCm.gPEoRgUczOT9CsxnwiBLU9XN9akBSg."
                        tokenSigningKey: "NNKuuEiu0FwwdriTlHyn6sWSJgPEc9Ri"
                    ingress:
                        enabled: {{ not .Values.route.enabled }}
                        ingressClassName: "openshift-default"
                        tls:
                            selfSignedCert: {{ .Values.kargo.selfSignedCert }}
                    resources:
                        requests: { cpu: "100m", memory: "128Mi" }
                        limits:   { cpu: "500m", memory: "512Mi" }
                controller:
                    argocd:
                        namespace: "argocd"
                    resources:
                        requests: { cpu: "100m", memory: "128Mi" }
                        limits:   { cpu: "500m", memory: "512Mi" }
                webhookServer:
                    resources:
                        requests: { cpu: "50m",  memory: "64Mi"  }
                        limits:   { cpu: "200m", memory: "256Mi" }

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
