{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kargo
  namespace: kargo
spec:
  host: {{ .Values.route.host | quote }}
  to:
    kind: Service
    name: kargo-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

{{- end }}