apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-prod
  namespace: argocd
spec:
  project: app1
  source:
    repoURL: https://github.com/NC-R/argocd
    path: apps/app1/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
