apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-customers
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/NC-R/argocd.git
        revision: main
        files:
          - path: infra/customers/*/*.yaml     # eine Datei je Kunde×App
  template:
    metadata:
      name: '{{name}}-{{app}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: app1=reg.rsn-okd.netcloud.lab:8880/app1/app1
        argocd-image-updater.argoproj.io/app1.allow-tags: regexp:^prod-
        argocd-image-updater.argoproj.io/app1.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: '{{app}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source:
        repoURL: https://github.com/NC-R/argocd.git
        targetRevision: main
        path: apps/{{app}}
        helm:
          valuesObject:
            route:
              host: '{{name}}.{{app}}.{{baseDomain}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
