apiVersion: v1
kind: Namespace
metadata:
  name: kargo
  labels:
    environment: staging
    managed-by: argocd
    purpose: apps
  annotations:
    openshift.io/display-name: "Kargo Deployment"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kargo-quota
  namespace: kargo
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
