apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: argocd
  labels: { app: app1 }
spec:
  replicas: 1
  selector:
    matchLabels: { app: app1 }
  template:
    metadata:
      labels: { app: app1 }
    spec:
      containers:
        - name: app1
          image: reg.rsn-okd.netcloud.lab:8880/app1/app1@sha256:25f28e2d1668c9662767e7202a380fd5e9eb13773a97628ac5d0117ac372a611
          ports:
            - name: http
              containerPort: 8080
          # optional, aber sinnvoll in OpenShift:
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          # readiness/liveness optional, falls du Pfade hast:
          # readinessProbe:
          #   httpGet: { path: /health, port: http }
          #   initialDelaySeconds: 5
          # livenessProbe:
          #   httpGet: { path: /health, port: http }
          #   initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: argocd
  labels: { app: app1 }
spec:
  selector:
    app: app1
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app1
  namespace: argocd
spec:
  to:
    kind: Service
    name: app1
  port:
    targetPort: http   # immer den Service-PortNAMEN referenzieren
  tls:
    termination: edge
