# Standard-Image-Definition (wird vom ArgoCD Image Updater überschrieben)
image:
  repository: quay.io/openshift/origin-hello-openshift
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"


route:
  enabled: true
  host: ""    # Wird im ApplicationSet gesetzt

service:
  type: ClusterIP
  port: 80
