apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: dev
spec:
  project: app1
  source:
    repoURL: https://github.com/NC-R/argocd
    path: apps/app1/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
