apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-dev
  namespace: argocd
spec:
  project: app2
  source:
    repoURL: https://github.com/NC-R/argocd
    path: apps/app2/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
